title = "scribble"

# The URL the site will be built for
base_url = "/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
smart_punctuation = true

[markdown.highlighting]
highlight_code = true
style = "inline"
light_theme = "gruvbox-light-hard"
dark_theme = "gruvbox-dark-hard"

[extra]
# menu displayed in the top bar
menu = [
  {url = "/markdown-overview", name = "markdown"},
  {url = "/animal_cards", name = "card view"},
  {url = "/blog", name = "blog"},
]

# give credit to zola and the theme in footer
credit = true
# display copyright notice in the footer
copyright = "jzbor"
# display an additional third footer item
#custom_footer = ""

# Disallow known LLM-scrapers in robots.txt
robots_txt.no_llm = false
